version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        depends_on:
            - db

    web:
        image: nginx:alpine
        container_name: laravel_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8025:8025"
    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bookingapp
            MYSQL_USER: user
            MYSQL_PASSWORD:
        volumes:
            - db_data:/docker/mysql/data:/var/lib/mysql
volumes:
    db_data:
